version: '3.8'

services:
  release:
    image: sororiri/entto_blog_front_release:latest
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - 80:80

  dev:
    image: sororiri/entto_blog_front_dev:latest
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 80:3000
